# Generated by Django 2.0.7 on 2018-07-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20180722_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
