# Generated by Django 2.0.7 on 2018-07-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='purpose',
            field=models.CharField(max_length=500),
        ),
    ]
