# Generated by Django 2.0.7 on 2018-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20180726_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='purpose',
            field=models.TextField(max_length=500),
        ),
    ]
