# Generated by Django 2.0.7 on 2018-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_auto_20180726_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='purpose',
            field=models.TextField(max_length=300),
        ),
    ]
