# Generated by Django 2.0.7 on 2018-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_auto_20180730_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='purpose',
            field=models.TextField(max_length=200),
        ),
    ]
